language: minimal
os: osx
before_install:
    - sudo spctl --master-disable # So that VirtualBox can be installed without failing
script:
    - make -B ~
    - make -B ~ # test that running it twice won't break anything
    - travis_wait 60 brew bundle --global
    - travis_wait 60 make ~/.atom/packages
