language: minimal
os: osx
before_install:
    - sed -i '' '/cask "virtualbox"/g' dots/.Brewfile # virtualbox cannot be tested due to the kernel extension
script:
    - make -B ~
    - make -B ~ # test that running it twice won't break anything
    - travis_wait 60 brew bundle --global
    - travis_wait 60 make ~/.atom/packages
